### ISSUE TITLE
Como Usar?

### ISSUE THREAD

**Issue by C-Miriane** [maykbrito/wikipedia-api-node#1]
Oi, já estou usando o Video-Maker - Projeto do Felipe, mas a busca é inglês, e achei muito bacana essa nova possibilidade de "deixar" em Português, porém não entendo praticamente como funciona , poderia me dizer qual o passo a passo?

**Comment by maykbrito** [comment]
Opa!

Lá no arquivo api.js que está na pasta wikipedia, a segunda linha é onde a gente pega os dados da api oficial do wikipedia.

```js
const wikipediaApiUrl = 'https://pt.wikipedia.org/w/api.php
```

Já está fazendo a busca em português, pois tem esse `//pt.wikipedia` ... se a gente tirar o `pt` ele não faz as buscas em português.

**Entretanto**, o robô está **conversando** com a gente em inglês.

Caso a gente queira que o robô faça perguntas em português, teríamos que reescrever partes do código onde ele pergunta. Por exemplo: no terms.js que está na pasta wikipedia

```js
readline.keyInSelect(optionsTerms, 'Confirm Your Term Search or Select One :')
```

Consegui responder sua dúvida?

**Comment by C-Miriane** [comment]
Muito obrigada pela atenção em responder @maykbrito , mas infelizmente ainda sou iniciante e não entendo bem como funciona. No caso, queria saber se era possível fazer alguma modificação dentro do Projeto do Felipe que mudasse o resultado para Português ou saber se é possível usar o que você fez lá dentro para rodar tudo junto? talvez esteja confundindo tudo, mas não entendo bem aí é difícil explicar, mas o resultado buscado seria o vídeo final com legendas em Português.

**Comment by maykbrito** [comment]
>  No caso, queria saber se era possível fazer alguma modificação dentro do Projeto do Felipe que mudasse o resultado para Português

Sim! Vou explicar.

Passo 1
---

No projeto do Fil, abra o arquivo: [robots/text.js](https://github.com/filipedeschamps/video-maker/blob/master/robots/text.js)

Procura a linha onde está essa parte do código.

```js
const wikipediaResponse = await wikipediaAlgorithm.pipe(content.searchTerm)
```

Aí vc vai apagar essa linha acima e adicionar essa abaixo:

```js
const wikipediaResponse = await wikipediaAlgorithm.pipe({
    "lang" : "pt",
    "articleName": content.searchTerm
})
```

Bom.. feito isso, o Wikipedia já irá retornar as buscas tudo em português.

Porém, o Watson não vai entender, pois ele entende as coisas em Inglês.
Então, bora dizer pro Watson: "Hey Watson, pesquisa em português por favor!"

Passo 2
---

No mesmo arquivo que fizemos a alteração acima, procura a linha

```js
nlu.analyze({
        text: sentence,
        features: {
          keywords: {}
        }
```

e troque por essa:

```js
nlu.analyze({
        text: sentence,
        features: {
          keywords: {}
        },
        language: 'pt',
```

Passo 3
---

Torcer pra dar certo, pois, estou explicando sem testar ahahaha

---

> ou saber se é possível usar o que você fez lá dentro para rodar tudo junto?

Sim também rsrsrs. Mas acredito que a solução acima já dê certo pra você =)

**Comment by C-Miriane** [comment]
Oi @maykbrito não tinha visualizado. Muito obrigada pela explicação. Estou "enroscada" com o After Effects ainda. Depois que colo o "link" para autorizar acessar a conta e subir o vídeo ele retorna erro dizendo que não encontrou o output.mov. As imagens até aparecem na pasta content, mas esse arquivo não. Estava tentando com AF4, mas não reconhece o template....tentei baixar o AF6, porém a máquina que estou usando no momento é 32bit...aí já viu...complica tudo. Vou ver oq faço aqui, aí terminando já faço a mudança para o Português conforme vc explicou...acho que vai dar certo sim :), mas volto aqui para contar daí....Obrigada novamente!

**Comment by maykbrito** [comment]
Não há de que!!

Tomara que dê certo !!

**Comment by 8uch3ch4** [comment]
Boa tarde @maykbrito 

Estou tentando fazer a mesma coisa, deixa do jeito que vi no Gif que você fez, mas bem leigo no assunto de programação teria como me ajudar ? 
![erro1](https://user-images.githubusercontent.com/50780009/58197518-d3b65980-7ca2-11e9-8e48-7e026238d324.png)

as duas partes alteradas 

  async function fetchWatsonAndReturnKeywords(sentence) {
    return new Promise((resolve, reject) => {
      nlu.analyze({
        text: sentence,
        features: {
          keywords: {}
        },
        language: 'pt',
        }
      }, (error, response) => {
        if (error) {
          reject(error)
          return
        }

----------------------

async function fetchContentFromWikipedia(content) {
    console.log('> [text-robot] Fetching content from Wikipedia')
    const algorithmiaAuthenticated = algorithmia(algorithmiaApiKey)
    const wikipediaAlgorithm = algorithmiaAuthenticated.algo('web/WikipediaParser/0.1.2')
    const wikipediaResponse = await wikipediaAlgorithm.pipe({
      "lang" : "pt",
      "articleName": content.searchTerm
  })
    const wikipediaContent = wikipediaResponse.get()

    content.sourceContentOriginal = wikipediaContent.content
    console.log('> [text-robot] Fetching done!')
  }

Obrigado pela ajuda

**Comment by maykbrito** [comment]
> Boa tarde @maykbrito
> 
> Estou tentando fazer a mesma coisa, deixa do jeito que vi no Gif que você fez, mas bem leigo no assunto de programação teria como me ajudar ?
> ![erro1](https://user-images.githubusercontent.com/50780009/58197518-d3b65980-7ca2-11e9-8e48-7e026238d324.png)
> 
> as duas partes alteradas
> 
> async function fetchWatsonAndReturnKeywords(sentence) {
> return new Promise((resolve, reject) => {
> nlu.analyze({
> text: sentence,
> features: {
> keywords: {}
> },
> language: 'pt',
> }
> }, (error, response) => {
> if (error) {
> reject(error)
> return
> }
> 
> async function fetchContentFromWikipedia(content) {
> console.log('> [text-robot] Fetching content from Wikipedia')
> const algorithmiaAuthenticated = algorithmia(algorithmiaApiKey)
> const wikipediaAlgorithm = algorithmiaAuthenticated.algo('web/WikipediaParser/0.1.2')
> const wikipediaResponse = await wikipediaAlgorithm.pipe({
> "lang" : "pt",
> "articleName": content.searchTerm
> })
> const wikipediaContent = wikipediaResponse.get()
> 
> ```
> content.sourceContentOriginal = wikipediaContent.content
> console.log('> [text-robot] Fetching done!')
> ```
> 
> }
> 
> Obrigado pela ajuda

oi @8uch3ch4 tudo bem?


Conforme a imagem do seu erro, está dizendo que está faltando um `)` . Parece que é o parentesis de  fechamento dessa parte do `nlu.analyze({...})`

Olha o código abaixo com o último parentesis, e perceba que no código que vc me enviou, não tem ele.

```js
async function fetchWatsonAndReturnKeywords(sentence) {
  return new Promise((resolve, reject) => {
    nlu.analyze({
      text: sentence,
      features: {
        keywords: {}
      },
      language: 'pt',
      })
```

---- 

ENTRETANTOOOO hehehe

Eu fiz uma baita atualização no projeto.

Caso você baixe a nova atualização dele muita coisa vai ter mudado tá?

Nessa atualização nova, mudar o idioma, é mais simples. 

Coloquei detalhes no README.md do projeto com o passo a passo para usar a linguagem em português.

**Comment by maykbrito** [comment]
oi @8uch3ch4 

Eu tinha acabado de mandar uma possível solução mas já apaguei kkk... 

Bom... assim.. a mensagem de erro do seu print é que está faltando um parentesis de fechamento `)`. Em alguma parte do código está faltando isso. 

A mensagem está dizendo que erro está em `new Script` na linha 80 do arquivo `vm.js`

É um simples erro de sintaxe, ou seja, as vezes a gente come uma virgula, um parentesis, e é normal isso =)
